language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install libgtest-dev valgrind lcov rubygems
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  - sudo gem install coveralls-lcov json

before_script:
  - pwd && mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_COVERAGE=On ..

script: make testsuites && make test

after_success:
  - lcov --capture --directory src/core --output-file coverage_full.info
  - lcov --remove coverage_full.info "*/include/*" "*/generated/*" "*.l" "*.cc" -o coverage_clean.info
  - coveralls-lcov coverage_clean.info
